name: Build KivyMD APK

on:
  push:
    branches: [ main ]
  workflow_dispatch: # <- lets you run manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Buildozer global directories
        uses: actions/cache@v4
        with:
          path: |
           .buildozer
            ~/.buildozer
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer -v android debug
          buildozer_version: master

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: LoveNotes-${{ github.run_number }}.apk
          path: bin/*.apk
